/poll command: when use poll command, bot will respond the embedded message with polling options
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #100
Opened 2023-05-21 09:06 UTC by Johnny850807

## Why need this change? / Root cause: 
- #98 
## Changes made:
- when use poll command, bot will respond the embedded message with polling options 
- work in progress
## Test Scope / Change impact:
- `/poll`

2023-05-22 08:26 UTC, frankvicky approved these changes
LGTM

2023-06-04 08:46 UTC, Wally5077 requested changes
Review done.

2023-06-04 08:46 UTC, Wally5077 commented on poll/src/main/kotlin/tw.waterballsa.utopia.poll/PollCommandListener.kt
> +        return PollingSetting(time!!, timeUnit, question, options)
改在宣告處使用 `!!`

2023-06-04 08:46 UTC, Wally5077 commented on poll/src/main/kotlin/tw.waterballsa.utopia.poll/PollCommandListener.kt
> +            if (userId == jda.selfUser.id) {
NIT：在 `MessageReactionAddEvent` 和 `MessageReactionRemoveEvent` 的父類開一個回傳 boolean 的擴充方法

2023-06-04 08:46 UTC, Wally5077 commented on poll/src/main/kotlin/tw.waterballsa.utopia.poll/PollCommandListener.kt
> +    }.joinToString("\n")
1. `System.lineSeparator()`
2. static import

2023-06-04 08:46 UTC, Wally5077 commented on poll/src/main/kotlin/tw.waterballsa.utopia.poll/PollCommandListener.kt
> +                            .setColor(Color.BLUE)
`static import`

2023-06-04 08:46 UTC, Wally5077 commented on poll/src/main/kotlin/tw.waterballsa.utopia.poll/PollCommandListener.kt
> +                    .joinToString("\n")
ditto `System.lineSeparator()`

2023-06-09 17:37 UTC, Wally5077 approved these changes
LGTM

2023-06-09 17:37 UTC, merged