:sparkles: 實作俄羅斯輪盤
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #128
Opened 2023-06-06 15:53 UTC by Anri-Hsuan

## Why need this change? / Root cause: 
- 新兵任務
## Changes made:
- russian-roulette
## Test Scope / Change impact:
- none

### Summary by OpenAI

Release Notes:

- New Feature: Added a new module for Russian Roulette game and its Maven POM file.
- New Feature: Implemented the logic for a Russian roulette game using Kotlin.
- New Feature: Added a new feature to the codebase, implementing a Russian Roulette game using Discord's API.
- Dependency Update: Added a new dependency to the project, `russian-roulette`.

> "A new game of chance has arrived,
> With Kotlin code that's been derived.
> Discord's API now joins the fray,
> And dependencies have come to play."

2023-06-07 03:08 UTC, Wally5077 requested changes
Review done.

2023-06-07 03:08 UTC, Wally5077 commented on russian-roulette/src/main/kotlin/tw/waterballsa/utopia/russianroulette/RouletteGame.kt
> +    fun pullTrigger(): Boolean = roulette[currentTurn--]
NIT：應該拆分開「開槍」和「告知遊戲結束」兩個動作，而非合而為一

2023-06-07 03:08 UTC, Wally5077 commented on russian-roulette/src/main/kotlin/tw/waterballsa/utopia/russianroulette/RussianRouletteListener.kt
> +                .timeout(1, TimeUnit.MINUTES)
static import

2023-06-07 03:08 UTC, Wally5077 commented on russian-roulette/src/main/kotlin/tw/waterballsa/utopia/russianroulette/RussianRouletteListener.kt
> +            playerIdToGame.remove(player.id)
NIT：按照下方寫法，可以在發送訊息後，移除玩家遊戲
```kotlin
reply("你已中彈，遊戲結束").queue { playerIdToGame.remove(player.id) }
```

2023-06-09 17:44 UTC, Johnny850807 approved these changes
LGTM

2023-06-09 18:47 UTC, Wally5077 requested changes
Review done.

2023-06-09 18:47 UTC, Wally5077 commented on russian-roulette/src/main/kotlin/tw/waterballsa/utopia/russianroulette/RouletteGame.kt
> +        }
## 情境：
**變數 roulette** 是「彈倉」
而 **pullTrigger** 是「將彈倉下一顆子彈，推到新的子彈擊發位置」
也就是 `currentTurn--` 改變「彈倉子彈位置」的邏輯

---
## 目標：
遊戲結束條件是「子彈擊中玩家」，意即「當前彈倉是否有子彈」

---
## 問題：
那麼確認「當前彈倉是否有子彈」，應該存在哪裡呢

2023-06-09 18:47 UTC, Wally5077 commented on russian-roulette/src/main/kotlin/tw/waterballsa/utopia/russianroulette/RouletteGame.kt
> +        isGameOver = true
是不是還有其他方式，可以不用額外設置 `isGameOver` 屬性
也能告訴函數調用者「遊戲是否結束」了呢

2023-06-26 14:53 UTC, Wally5077 submitted a review, later dismissed
LGTM

2023-06-26 14:54 UTC, frankvicky submitted a review, later dismissed
LGTM

2023-06-26 15:22 UTC, Wally5077 approved these changes
**LGTM**

2023-06-26 15:51 UTC, merged