feat: add rockpaperScissors feature
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #129
Opened 2023-06-07 08:12 UTC by zazachan425

## Why need this change? / Root cause: 
-新增剪刀石頭布小遊戲
## Changes made:
-create rock-paper-scissors module, adding dependency to main/pom.xml and root/pom.xml
## Test Scope / Change impact:
-

2023-06-07 08:41 UTC, frankvicky requested changes
Review Done
多餘的空白請刪除

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +//import net.dv8tion.jda.api.interactions.components.buttons.Button
沒有用的 import 要刪除

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +const val PAPER = "\uD83E\uDD1A布"
請修飾存取範圍，依據需要選擇 `private` 或 `internal`

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +        return fullCommandName == ROCKPAPERSCISSORS_COMMAND
inline

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +        return "${ROCKPAPERSCISSORS_COMMAND}-${punch}"
inline
另外這邊可以不需要大括號

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +        return button.id!!.split("-")[1].toInt()
inline
`button.id!!.split("-")[1].toInt()` -> `button.id!!.split("-").last().toInt()`

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +        return (0..2).shuffled().first()
inline

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +const val EVEN = "\uD83C\uDDEA \uD83C\uDDFB \uD83C\uDDEA \uD83C\uDDF3"
ditto
修飾存取範圍

2023-06-07 08:41 UTC, frankvicky commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +        return button.id!!.contains(ROCKPAPERSCISSORS_COMMAND)
inline

2023-06-07 09:44 UTC, frankvicky approved these changes
LGTM

2023-06-07 15:12 UTC, Wally5077 requested changes
Review done.

2023-06-09 19:18 UTC, Wally5077 requested changes
Review done.

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +class RockPaperScissorsListener(private val wsa: WsaDiscordProperties) : UtopiaListener() {
檔案名稱和 `RockPaperScissorsListener` 一致

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +private const val ROCKPAPERSCISSORS_COMMAND = "rock-paper-scissors"
常數全大寫名稱，每個單字以**底線**隔開

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +enum class GameResult(val msg: String) {
`msg` -> `message`

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +                    🎯結果 -> ${result.msg}
GameResult 一樣覆寫 toString 後，這邊可以直接給 GameResult 了

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +    private fun ButtonInteractionEvent.isValidButtonId(): Boolean = button.id!!.startsWith(ROCKPAPERSCISSORS_COMMAND)
1. **isRockPaperScissorButtonId**
2. 如果 buttonId 以及是 Punch 的名字了，那這邊也須相應調整一下~

2023-06-09 19:18 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissors.kt
> +    private fun ButtonInteractionEvent.getPlayerPunch(): Punch = button.id!!.split("-").last().toPunch()
如果 buttonId 以及是 Punch 的名字了，那這邊也須相應調整一下~

2023-06-10 04:22 UTC, Wally5077 requested changes
Review done.

2023-06-10 04:22 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissorsListener.kt
> +    private fun createButtonId(punch: Punch): String = "${punch.name}-${punch.ordinal}"
1. 直接擴充成 Punch 的方法
```kotlin
private fun Punch.toButtonId() : String = "$name-$ordinal"
```

---
2. 由於下方也有使用到這個方法，你可以將這方法放在底下

2023-06-10 04:22 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissorsListener.kt
> +        Punch.values().map { createButtonId(it) }.contains(button.id!!)
把 map 換成用 any 做到就可以了

2023-06-10 04:22 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/RockPaperScissorsListener.kt
> +    private fun String.toPunch(): Punch = Punch.valueOf(this)
1. 兩個合併再一起就好了
2. **getPunchName** 方法裡面不用呼叫 `this`

2023-06-10 04:22 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +}
GameResult 可以改放「贏家」、「輸家」以及「是否平手」，讓 Listener 負責顯示就好
就不要用 Domain 的 RockPaperScissors 還有 **顯示畫面結果** 的責任了

2023-06-10 04:22 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +}
這個放在 RockPaperScissors 類別底下

2023-06-10 04:40 UTC, Wally5077 requested changes
Review done.

2023-06-10 04:40 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +    fun throwAPunch(myPunch: Punch, enemyPunch: Punch): GameResult {
**throwAPunch** -> **punch**

2023-06-10 04:40 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +    companion object;
分號幫我拿掉一下~

2023-06-10 04:40 UTC, Wally5077 commented on rock-paper-scissors/src/main/kotlin/tw/waterballsa/utopia/rockpaperscissors/domain/RockPaperScissors.kt
> +            (enemyPunch.ordinal + 1).mod(Punch.values().size) == myPunch.ordinal -> GameResult.WIN
NIT：上一下註解，表示這邊的餘數算法「為什麼可以判斷輸贏」

2023-06-10 15:55 UTC, wow890209 submitted a review, later dismissed
very well! LTGM

2023-06-10 15:56 UTC, Wally5077 approved these changes
LGTM

2023-06-10 15:58 UTC, wow890209 approved these changes
approve

2023-06-10 15:59 UTC, merged