create utopia-gamification-quest feature
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #133
Opened 2023-06-10 18:03 UTC by wow890209

## Why need this change? / Root cause: 
- 初版任務系統
- 新增三個新手任務：解鎖學院、自我介紹、到閒聊區打招呼
## Changes made:
- 實現任務系統邏輯
- toggle off
- bugfix：member在私人頻道為null，在PersonalLeave.kt的第70行。增加null的判斷
## Test Scope / Change impact:
-

2023-06-11 04:31 UTC, frankvicky requested changes

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +open class Action {
改成抽象類

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +    }
改成抽象方法

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +                if (channelId == criteria.selfIntroductionChannelId && context matches criteria.regex) {
請把 `if` 裡面的條件式封裝成一個方法

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +                if (channelId == criteria.discussionChannelId && criteria.times == criteria.discussionTimes) {
ditto

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +                criteria.times += 1
這個請在類別內部撰寫一個專門執行 `criteria.times += 1`  的方法，不要直接存取屬性做操作。

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    }
inline

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +        val criteria = quest.criteria.firstOrNull { action.match(it) } ?: return false
這裡用 `find` 更有表達力

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    private fun allCriteriaComplete() {
這個命名想表達甚麼？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Player.kt
> +class Player(val id: String, var name: String = " ", var exp: Long = 0, level: Int = 1) {
問：name 預設值是一個空白？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Quest.kt
> +import tw.waterballsa.utopia.utopiagamificationquest.domain.quests.quest
這上面的 import 你沒一個有在用，為什麼要留著？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/quests/QuestBuilder.kt
> +class Quests(val wsa: WsaDiscordProperties)
為什麼有第二個 `Quest` 類別？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/quests/QuestBuilder.kt
> +    lateinit var criterias: List<Action.Criteria>
typo
還有為什麼上面都是 `lateinit` ？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Quest.kt
> +)
`Reward` 是 `Quest` 之下的從屬概念嗎？還是獨立的？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/DummyDataBase.kt
> +            missions[it.hashCode().toString()] = it
你有覆寫 `hashCode` 嗎？

2023-06-11 04:31 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/DummyDataBase.kt
> +    private val missions = mutableMapOf<String, Mission>()
這裡順序重要嗎？不重要請改成 `hashMapOf`

2023-06-11 06:24 UTC, Wally5077 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt
> +            val member = member ?: return
Well done.

2023-06-11 07:12 UTC, Wally5077 requested changes
Review done.

2023-06-11 07:12 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +                criteria.times += 1
這樣才不會破壞封裝

2023-06-11 07:12 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Action.kt
> +        }
ditto when

2023-06-11 07:12 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    private fun allCriteriaComplete() {
方法命名多以動詞開頭

2023-06-11 07:12 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/DummyDataBase.kt
> +            missions[it.hashCode().toString()] = it
mission 沒有一個可辨識的 id 之類的嗎？

2023-06-12 09:52 UTC, frankvicky requested changes

2023-06-12 10:00 UTC, frankvicky requested changes

2023-06-12 15:00 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            mission.player.gainExp(mission.quest.reward.exp)
為什麼 mission 的 quest 給 mission 的 player reward 經驗值要這麼麻煩？
封裝起來這段邏輯就好了吧？

2023-06-15 13:01 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +class Mission(val player: Player, val quest: Quest, var missionId: Int = 0) {
```kotlin
class Mission(val missionId: UUID, val player: Player, val quest: Quest) {
    constructor(val player: Player, val quest: Quest) : this(UUID.randomUUID(), player, quest)
}
```

2023-06-15 13:04 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/PlayerDataBase.kt
> +    fun putIfAbsent(player: Player) {
`registerPlayer`

2023-06-15 13:04 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/PlayerDataBase.kt
> +
1. `players.computeIfAbsent(player.id) { it -> player}`
2. 多一行

2023-06-15 13:07 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +
多一行

2023-06-15 13:10 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageReactionAction.kt
> +    }
1. `Suffice` 應該拼錯了
2. 我想只需要下方程式碼就好了
```kotlin
if (criteria.isSuffice(this)) {
    criteria.complete()
}
```

2023-06-15 13:23 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/DummyDataBase.kt
> +        missionRepository.saveMission(mission)
```kotlin
missionRepository.saveMission(mission)
```

2023-06-15 13:33 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +
```kotlin
val player = repository.savePlayer(Player(user.id, user.name))
```

2023-06-15 13:44 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/MissionDataBase.kt
> +        }
```kotlin
return missions.computeIfAbsent(mission.id) { it -> mission }
```

2023-06-15 13:54 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/DummyDataBase.kt
> +        val player = playerRepository.findPlayerById(playerId) ?: return listOf()
刪除

2023-06-16 02:31 UTC, Wally5077 requested changes
Review done.

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/MissionDataBase.kt
> +        return missions.filter { it.value.player.id == playerId }.values.toList()
```kotlin
missions.values.filter { it.player.id == playerId }.toList()
```

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repository/MissionDataBase.kt
> +        missions[mission.id] = mission
這邊的邏輯如下
```
1. 按照 mission id 搜尋 missions 對應的 mission
    1-1. 若是無，則新增
    1-2. 若是有，則編輯
```

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    }
inline

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    constructor(player: Player, quest: Quest) : this(UUID.randomUUID(), player, quest)
static import `randomUUID()`

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            val mission = missions.find { it.quest.title == questTitle } ?: return
這似乎可以合併成一行
```kotlin
val mission = repository.findMissionsByPlayerId(playerId)
                .find { it.quest.title == questTitle } ?: return
```

2023-06-16 02:31 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +                repository.saveMission(nextMission)
這一段和 slashCommand 的程式碼重複了，開一個方法讓這段邏輯能重用吧

2023-06-16 11:09 UTC, Wally5077 requested changes
Review done.

2023-06-16 11:09 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +        return mission
`return repository.saveMission(mission)`

2023-06-16 11:09 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +                ).queue()
用 `with(mission)` 包起來一下，並將 button 排版排好

2023-06-17 06:29 UTC, Wally5077 requested changes
Review done.

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +    fun updateProgress(action: Action): Boolean {
為什麼需要回傳 `true` or `false` ?

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            val missions = repository.findMissionsByPlayerId(user.id).ifEmpty { return }
直接找出尚未完成的任務吧
```kotlin
val uncompletedMissions = findUncompletedMissionsByPlayerId(user.id).ifEmpty { return }
```

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            val missions = repository.findMissionsByPlayerId(playerId).ifEmpty { return }
ditto 尚未完成的任務

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            missions.filter { !it.isCompleted() && it.match(action) }
找出尚未完成的任務就不用過濾 `!isCompleted()` 了

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            missions.filter { !it.isCompleted() && it.match(action) }
ditto 不用過濾 !isCompleted() 了

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +        action.updateProgress(quest.criteria)
`action.execute`

2023-06-17 06:29 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +                    .onEach { it.updateProgress(action) }
it.carryOut(action)

2023-06-17 11:26 UTC, Wally5077 approved these changes
LGTM

2023-06-17 16:12 UTC, frankvicky approved these changes

2023-06-17 16:13 UTC, merged