add TutorialQuest
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #143
Opened 2023-06-21 10:35 UTC by wow890209

## Why need this change? / Root cause: 
- 1.ReplyToAnyoneInCareerAdvancementTopicChannelQuest 
- 2.SendContainsImageMessageInEngineerLifeChannelQuest 
- 3.SendMessageInVoiceChannelQuest
## Changes made:
- 
## Test Scope / Change impact:
-

2023-06-21 16:10 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +            message.referencedMessage?.let { true } ?: false,
這是不是可以直接判斷這值非 null 就好了？

2023-06-22 06:26 UTC, frankvicky submitted a review, later dismissed
LGTM

2023-06-22 15:46 UTC, Wally5077 requested changes
Review done.

2023-06-22 15:46 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +        val voicePopulation: Int,
`numberOfVoiceChannelMembers`

2023-06-22 15:46 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +        val containsImage: Boolean,
`hasImage`

2023-06-22 15:46 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +        val isReplied: Boolean,
`hasReplied`

2023-06-22 15:46 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +        private val voicePopulation: Int = 0,
ditto `hasReplied` & `hasImage` & `numberOfVoiceChannelMembers`

2023-06-22 15:46 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +        private val goalCount: Int,
**Well done.**

2023-06-23 07:48 UTC, Wally5077 approved these changes
LGTM

2023-06-23 07:48 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/quests/TutorialQuests.kt
> +const val anyChannel = ""
Q：這在做什麼？

2023-06-23 07:54 UTC, wow890209 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/quests/TutorialQuests.kt
> +const val anyChannel = ""
就是不指定頻道id，使任何頻道id都可以讓條件過關

2023-06-23 07:54 UTC, merged