create tracking channel message count feature module
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #151
Opened 2023-06-29 13:03 UTC by wow890209

https://github.com/Waterball-Software-Academy/WSA-Utopia-Discord-Bot/issues/149

## Why need this change? / Root cause: 
- 依照buffer需求新增的機器人功能
## Changes made:
-
## Test Scope / Change impact:
-

2023-06-29 15:24 UTC, Wally5077 requested changes
Review done.

2023-06-29 15:24 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/domain/UsersMessageCount.kt
> +//}
註解就刪除了~

2023-06-30 13:58 UTC, Wally5077 requested changes
**Review done.**

2023-06-30 13:58 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +
這如果沒有用就刪除
如果有用，就上說明

2023-06-30 13:58 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        )
寫在 `commands()`

2023-06-30 13:58 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        private const val RETRIEVE_COMMAND_NAME = "retrieve"
UtopiaListener 外

2023-06-30 13:58 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        private const val USER = "user"
UtopiaListener 外

2023-07-01 05:20 UTC, frankvicky requested changes

2023-07-01 05:20 UTC, frankvicky commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        private val jsonMapper = ObjectMapper()
這邊依賴注入

2023-07-27 02:06 UTC, Wally5077 requested changes
**Review done.**

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +                }
不用 lambda 展開，直接 return

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +            }
這是多餘的，前面有防呆了

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        val day = getOption(DAY)?.asInt ?: return Query.IGNORE
**Query.IGNORE** 是個一眼就無法明白的寫法，**Query.IGNORE** 想要做什麼？

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +            LocalDate.of(year, month, day)?.format(DATE_FORMAT) ?: return Query.IGNORE
Q：沒必要去 format 成字串吧？

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +            history.ifEmpty { return messages }
這是 **while** 條件式，那 **while** 外就應該宣告一個變數裝它

2023-07-27 02:06 UTC, Wally5077 commented on automatic-channel-comment-tracking/src/main/kotlin/tw/waterballsa/utopia/automaticchannelcommenttracking/AutomaticChannelCommentTrackingListener.kt
> +        var messageIterator = latestMessageId
**messageIterator** -> **latestMessageId**

2024-10-06 13:15 UTC, closed without merging