Feature/message cherry pick
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #156
Opened 2023-07-16 09:24 UTC by m1a2st

## Why need this change? / Root cause: 
- 可以把message 移動到thread
## Changes made:
- 增加/message cherry-pick指令
- 增加/message cherry-pick to指令
## Test Scope / Change impact:
- no test scope

#130

2023-07-18 07:51 UTC, frankvicky requested changes

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/CherryPickManager.kt
> +    private var users = mutableListOf<User>()
`val`

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/CherryPickManager.kt
> +        return users.any { it.id.value == userId }
`fun contains(userId: String): Boolean = users.any { it.id.value == userId }`

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/CherryPickManager.kt
> +    }
`fun getUser(userId: String): User? = users.find { it.id.value == userId }`

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +                                it.isContentNotBlank()
封裝成一個方法

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +    private fun SlashCommandInteractionEvent.replyEphemeralMessage(message: String) {
改成 `replyEphemerally`

2023-07-18 07:51 UTC, frankvicky commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/domain/SelectedRange.kt
> +    }
`fun isStartTimeAfterEndTime(): Boolean = startTime.isAfter(endTime)`

2023-07-18 09:05 UTC, Wally5077 requested changes
**Review done.**

2023-07-18 09:05 UTC, Wally5077 commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +            if (subcommandName == CHERRY_PICK) {
`when`

2023-07-18 09:05 UTC, Wally5077 commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +            if (subcommandName == CHERRY_PICK_TO) {
ditto `when`

2023-07-20 16:09 UTC, Wally5077 requested changes
**Review done.**

2023-07-20 16:09 UTC, Wally5077 commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +        cherryPickManager.register(User(userId), dateTimeRange)
**CherryPick**
```java
data class CherryPick(val cherryPickerId: String, val dateTimeRange: DateTimeRange)
```

2023-07-20 16:09 UTC, Wally5077 commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +        val endDateTime = endDate?.toTaiwanEpochMilli(0) ?: startDate.toTaiwanEpochMilli(1)
這裡還是使用 **OffsetDateTime**

2023-07-20 16:09 UTC, Wally5077 commented on message-cherry-pick/src/main/kotlin/tw/waterballsa/utopia/MessageCherryPickListener.kt
> +    private val cherryPickManager = CherryPickManager()
**CherryPickRepository**

2023-07-20 17:10 UTC, Wally5077 approved these changes
**LGTM**

2023-07-20 17:11 UTC, Wally5077 submitted a review, later dismissed
**LGTM**

2023-07-20 17:21 UTC, Wally5077 approved these changes
**LGTM**

2023-07-20 17:36 UTC, Wally5077 approved these changes
**LGTM**

2023-07-25 13:17 UTC, frankvicky approved these changes

2023-07-25 13:18 UTC, merged