add two tutorial quest。
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #157
Opened 2023-07-18 07:42 UTC by wow890209

## Why need this change? / Root cause: 
- 依照需求封裝訊息接收的情況
- 加入兩個新手任務，所有新手任務都已實作。
## Changes made:
-
## Test Scope / Change impact:
-

2023-07-18 08:30 UTC, Wally5077 requested changes
**Review done.**

2023-07-18 08:30 UTC, Wally5077 commented on main/src/main/resources/wsa.beta.properties
> +featured-videos-channel-link=https://discord.com/channels/1038654765896310804/1129663992323919902
1. 使用 The channel link pattern = `https://discord.com/channels/${guildId}/${channelId}`，之前的 link key 一起改掉~
2. 如果覺得要在外面一直寫這 pattern 很麻煩，就在先前的 extension 類別，擴充一個 toLink 的方法
```kotlin
val resumeCheckChannelLink = resumeCheckChannelId.toLink()
```

2023-07-18 08:30 UTC, Wally5077 commented on commons/src/main/kotlin/tw/waterballsa/utopia/commons/config/WsaDiscordProperties.kt
> +            featuredVideosChannelLink = getProperty("featured-videos-channel-link")
Q：這是問過 ChatGPT 後的命名嗎？

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/MessageSentListener.kt
> +
刪掉多餘的空行

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/MessageSentListener.kt
> +
ditto 空行

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/MessageSentListener.kt
> +
ditto 空行

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +}
enum

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +//因此，你可以將"準則"視為一個總的判斷原則，而這個原則下面可以有許多具體的規則或標準，用來幫助我們做出判斷或決定。
這附在 PR 裡面解釋

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +    private val regexRule: RegexRule = RegexRule.IGNORE,
那有沒有考慮 Rule 都是同個類，而讓 Criteria 聚合多種 Rule 呢

2023-07-18 08:30 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +                && regexRule.meet(action.context)
若是 Rule 都是同一種類，那麼程式碼可以如下：
```kotlin
rules.all { it.meet(action) }
```

2023-07-19 06:44 UTC, wow890209 commented on commons/src/main/kotlin/tw/waterballsa/utopia/commons/config/WsaDiscordProperties.kt
> +            featuredVideosChannelLink = getProperty("featured-videos-channel-link")
若你希望使用英文來命名"履歷健檢頻道"，可以考慮以下的一些命名：

"ResumeCheckChannel"
"CVReviewChannel"
"ResumeInspectionChannel"
"CVAnalysisChannel"

2023-07-20 03:05 UTC, frankvicky requested changes

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/ButtonInteractionAction.kt
>      }
inline

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +    }
inline

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +    }
inline

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +    }
inline

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/actions/MessageSentAction.kt
> +    }
inline

2023-07-20 03:05 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/quests/QuestBuilder.kt
> +    }
inline

2023-07-22 16:02 UTC, Wally5077 requested changes
**Review done.**

2023-07-22 17:03 UTC, Wally5077 approved these changes
**LGTM**

2023-07-22 17:09 UTC, merged