新增週訊息量統計功能
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #165
Opened 2023-07-26 15:55 UTC by m1a2st

## Why need this change? / Root cause: 
- want count message volume in this week
## Changes made:
- new /weekly-message-volume command
## Test Scope / Change impact:
- none
#137

2023-07-27 01:56 UTC, Wally5077 requested changes
**Review done.**

2023-07-27 01:56 UTC, Wally5077 commented on discord-impl-jda/src/main/kotlin/tw/waterballsa/utopia/jda/extensions/GenericCommandInteractionEventExtension.kt
> +    addOption(type, name, description, true)
**Well done**

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/WeeklyMessageVolumeListener.kt
> +        const val CHANNEL_NAME = "channel-name"
1. `private`
2. 有用到這個變數的擴充，放進 **WeeklyMessageVolumeListener**  裡

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/WeeklyMessageVolumeListener.kt
> +    private fun SlashCommandInteractionEvent.countWeeklyMessage() {
邏輯放進 **onSlashCommandInteraction** 裡就好，這函數是多開的

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/WeeklyMessageVolumeListener.kt
> +    getOptionAsStringWithValidation(CHANNEL_NAME, "channel name is invalid.") { it.isNotBlank() }!!
改成擴充屬性

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/WeeklyMessageVolumeListener.kt
> +    guild?.textChannels?.first { it.name.contains(getChannelName(), ignoreCase = true) }
**first** -> **find**

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/doamin/WeeklyRange.kt
> +        .toOffsetDateTime()
用成一行

2023-07-27 01:56 UTC, Wally5077 commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/doamin/WeeklyRange.kt
> +                .toTaiwanDateTime()
一周不是七天前的概念，一周的起始是周一
假如今天周四，那麼時間回溯到 7 天前
就會變成**上**周四，這就不是當週了吧？

因此，就命名上會有語意上的錯誤

2023-07-27 06:20 UTC, frankvicky requested changes

2023-07-27 06:20 UTC, frankvicky commented on weekly-message-volume/src/main/kotlin/tw/waterballsa/utopia/weeklymessagevolume/WeeklyMessageVolumeListener.kt
> +        }
合併

2023-07-28 14:33 UTC, Wally5077 submitted a review, later dismissed
**LGTM**

2023-07-28 14:38 UTC, frankvicky approved these changes

2023-07-28 15:53 UTC, Wally5077 approved these changes
**LGTM**

2023-07-28 15:54 UTC, merged