utopia mission save to  mongodb
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #167
Opened 2023-07-28 15:50 UTC by m1a2st

## Why need this change? / Root cause: 
- save mission to mongoDb
## Changes made:
- user to server can have a mission
## Test Scope / Change impact:
- none

2023-07-29 18:08 UTC, wow890209 requested changes
Review Down

2023-07-29 18:08 UTC, wow890209 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repositories/InMemoryMissionRepository.kt
> +//    }
因為我們是要全部替換掉 inMemoryRepository，所以這個 inMemoryRepository file 未來也不會再用，是多餘的。
刪掉他。

2023-07-29 18:18 UTC, wow890209 requested changes
review down.

2023-07-29 18:18 UTC, wow890209 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
>  }
因為 domain 不應該知道 data 的東西，所以需要把 toDocument 移動到 mongodb repository 裡面，使用擴充方法。

2023-07-30 05:59 UTC, frankvicky requested changes

2023-07-30 05:59 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +                    reply("已獲得新手任務，無法再次獲得。").setEphemeral(true).queue()
`.setEphemeral(true).queue()` 可以擴充

2023-07-30 05:59 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/UtopiaGamificationQuestListener.kt
> +                    reply("已經接取第一個任務，去私訊查看任務內容。").setEphemeral(true).queue()
ditto 可以擴充

2023-07-30 05:59 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +        state = State.CLAIMED
開一個`cancel()`方法

2023-07-30 05:59 UTC, frankvicky commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/repositories/MongodbMissionRepository.kt
> +            .firstOrNull { query.match(it) }
`find()`

2023-07-30 06:11 UTC, Wally5077 requested changes
**Review done.**

2023-07-30 06:11 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/domain/Mission.kt
> +        if (quest.criteria.isCompleted) {
我覺得 **action.execute(quest.criteria)** 可以回傳一個 **boolean**
表示「quest 的 criteria 是否完成」，這樣就不需要重新向 quest 的 criteria 確認「完成狀態」

2023-07-30 06:11 UTC, Wally5077 commented on utopia-gamification-quest/src/main/kotlin/tw/waterballsa/utopia/utopiagamificationquest/service/PlayerAcceptQuestService.kt
> +            ?: false
這邏輯只是「能否查到資料吧」，那只要判斷回傳值「是否為 null」即可

2023-07-30 08:16 UTC, Wally5077 submitted a review, later dismissed
**LGTM**

2023-07-30 08:18 UTC, wow890209 approved these changes

2023-07-30 11:22 UTC, frankvicky approved these changes

2023-07-30 13:50 UTC, merged