refactory player class and add hotfix player exp tool
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #206
Opened 2023-10-17 14:35 UTC by wow890209

## Why need this change? / Root cause: 
- fixed the experience value in the player repository, it should now reflect the total experience. 
## Changes made:
- add hotfix tool
- refactor player class
## Test Scope / Change impact:
-

2023-10-19 12:44 UTC, m1a2st requested changes

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +const val PLAYER_UPDATE_COMMAND_NAME = "playerupdate"
上面 `mission-log` 使用 Kebab case，這裡的 `playercheck` 跟 `playerupdate` 是否應該統一規則？

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +                SubcommandData(PLAYER_COMMAND_NAME, "check player exp"),
`PLAYER_COMMAND_NAME` 裡面是 playercheck ， `PLAYER_UPDATE_COMMAND_NAME` 是 playerupdate ，變數名稱是否統一，應改成 `PLAYER_UPDATE_COMMAND_NAME`

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +                SubcommandData(PLAYER_UPDATE_COMMAND_NAME, "check player exp"),
`check player exp` 這個指令的描述是否正確？

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        println("------------------------------")
無用的 print 請刪除

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +
空行移除

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        val allPlayer = playerRepository.findAll()
`allPlayer` 應為複數 `allPlayers`

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +                println(newExp)
ditto : `print` 移除

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        val allPlayer = playerRepository.findAll()
ditto allPlayers

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        println(list)
ditto : `print`

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        // 1 == 2
無法讓人理解的註解請刪除

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        var isBad = 0
`isOk` 跟 `isBad` 這種命名方式是用在 boolean 上面，這邊無法理解用意，要看到下面的程式才知道

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/HotFixTool.kt
> +        var list = ""
用來 print 的變數，請刪除

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/repositories/mongodb/repositoryimpl/MongodbPlayerRepository.kt
> +        Player.ExperiencePoints(level = level.toUInt(), totalExp = exp.toULong(), upgradeDate = levelUpgradeDate),
這邊可以 static import ?

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
> +    experiencePoints: ExperiencePoints = ExperiencePoints(level = 1u, totalExp = 0u, upgradeDate = now()),
ExperiencePoints 的中文是什麼？有沒有更好的英文命名？

2023-10-19 12:44 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
> +        val currentExp = if (level.toInt() <= LEVEL_ONE.level || totalExp < levelRange.previous!!.accExp) totalExp else totalExp - levelRange.previous.accExp
把這個複雜的邏輯，拆成人類可以理解的語言

2023-10-22 08:47 UTC, shmily7829 requested changes
Review done.

2023-10-22 08:47 UTC, shmily7829 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
> +        private set
1. `private set` 的屬性初始值請直接在變數宣告時賦值
2. `levelUpgradeDate` lateinit，在 gainExp 時才賦值

2023-10-22 08:47 UTC, shmily7829 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
>          activate()
`levelUpgradeDate` 是前一次升級時間，應該在升級時才更新時間

2023-10-22 08:47 UTC, shmily7829 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/repositories/mongodb/repositoryimpl/MongodbPlayerRepository.kt
> +
convert to expression body

2023-10-22 08:47 UTC, shmily7829 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagmification/quest/UtopiaGamificationQuestTest.kt
> +
1. 第一個和第二個測項都是測試同一件事，保留一個即可
2. 測試描述的 `player` 應給具體名稱：`playerA`
```
given new player -> given playerA
```

```
given level 3 and exp 650 player ->
given playerA level 3 and exp 650
```

2023-10-22 12:38 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
> +        private set
那要怎麼處理 document to domain 對 player 屬性賦值的情況？

2023-10-22 12:38 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/repositories/mongodb/repositoryimpl/MongodbPlayerRepository.kt
> +
這個已經沒用了，我刪掉了

2023-10-22 13:30 UTC, m1a2st requested changes
Review done

2023-10-22 13:30 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/Player.kt
> +    levelUpgradeDate: OffsetDateTime = now(),
為什麼 new Player 的時候，他的 `levelUpgradeDate` 就要給現在時間？這個 Player 還沒有升級，這個屬性卻有值是否不合邏輯。

2023-10-25 11:59 UTC, m1a2st approved these changes
LGTM

2023-10-27 08:35 UTC, Wally5077 requested changes
**Review done.**

2023-10-27 08:35 UTC, Wally5077 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/extensions/LevelSheet.kt
> +        fun isLevelUp(exp: ULong) = accExp > exp
請幫我改成 `isMatchLevel`

2023-10-29 06:15 UTC, Wally5077 approved these changes
**LGTM**

2023-10-29 06:18 UTC, shmily7829 approved these changes
LGTM

2023-10-29 06:20 UTC, merged