:real achievement-system
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #209
Opened 2023-10-22 07:42 UTC by shmily7829

## Why need this change? / Root cause: 
- add feature achievement-system
## Changes made:
- resloved #203 #204 
## Test Scope / Change impact:
- achievement-system

2023-10-22 12:24 UTC, wow890209 requested changes

2023-10-22 12:24 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/framework/listener/AchievementListener.kt
> +    }
想問這裡不用 queue 的原因

2023-10-22 12:26 UTC, wow890209 requested changes
Review down.

2023-10-22 12:26 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/framework/listener/AchievementListener.kt
> +    }
這裡不用 queue 的原因

2023-10-22 14:15 UTC, frankvicky requested changes

2023-10-22 14:15 UTC, frankvicky commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/application/usecase/ProgressAchievementUseCase.kt
> +        return achievement.achieve(this, refreshedProgression)
沒很長，空白刪掉，放一起吧

2023-10-22 14:15 UTC, frankvicky commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/domain/achievements/Achievement.kt
> +
ditto，刪除不必要空白

2023-10-22 14:15 UTC, frankvicky commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/domain/achievements/Achievement.kt
> +        return null
```kotlin
        return if (rule.isAchieved(player, progression)) {
            reward.reward(player)
            toAchieveEvent()
        } else null
```

2023-10-22 14:15 UTC, frankvicky commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/framework/listener/presenter/ProgressAchievementPresenter.kt
> +    override fun present(event: List<AchievementAchievedEvent>) {
參數名稱 `events`

2023-10-22 14:15 UTC, frankvicky commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/framework/listener/presenter/ProgressAchievementPresenter.kt
> +        }
`events.forEach { ... }`

2023-10-24 17:51 UTC, Wally5077 approved these changes
**LGTM**

2023-10-25 14:16 UTC, wow890209 approved these changes
LGTM

2023-10-27 01:05 UTC, frankvicky approved these changes

2023-10-29 05:20 UTC, merged