refactor assignPlayerQuestUsecase and add test
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #218
Opened 2023-10-30 12:06 UTC by wow890209

## Why need this change? / Root cause: 
-refactor assignPlayerQuestUsecase and add test
## Changes made:
-
## Test Scope / Change impact:
-

2023-10-31 14:05 UTC, shmily7829 requested changes
Review done

2023-10-31 14:25 UTC, m1a2st requested changes

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val presenter = AssignPlayerQuestTestPresenter(playerA.id, UNLOCK_QUEST_ID)
如果每一個測試都有使用到相同參數的 `request` 請改成共用屬性

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `success assign a unlock quest to player A`() {
使用 given when then 的語句會更好，或是上面加上 `@DisplayName` 並且一樣使用 give when then

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/usecase/AssignPlayerQuestUsecase.kt
> +        missionRepository.findPlayerMissionByQuestId(playerId, questId) != null
ditto : 如果用不到 mission ，在 missionRepository 開一個專門來判斷是否有資料的方法是否更好

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +private const val UNLOCK_QUEST_ID = 1
ditto : ditto : 如果 unlockAcademyQuestId 的值都固定為 1 的話，直接在 usecase 那邊賦值就好

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `fail assign a unlock quest to player A, because player A can not get quest repeatedly `() {
ditto : given when then

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        playerRepository.savePlayer(playerA)
ditto : 如果都有使用到 `playerA` ，請用 `@BeforeEach` 來幫忙寫入資料庫

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +            assignPlayerQuestUsecase.execute(request, presenter)
這邊的 given when then 很奇怪，我的理解應該是 given playerA has first quest when playerA assign first quest then playerA can't get same quest repeatedly

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val playerA = Player("A", "A")
ditto : playerA

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val request = AssignPlayerQuestUsecase.Request(playerId = playerA.id, questId = UNLOCK_QUEST_ID)
ditto : 如果每一個測試都有使用到相同參數的 request 請改成共用屬性

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val notExistQuest = -1
ditto : 如果 unlockAcademyQuestId 的值都固定為 1 的話，直接在 usecase 那邊賦值就好

我看只有測試有使用到 -1 如果直接寫在 usecase 的話，是否就不用有這個測試案例了

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +
ditto : playerA

2023-10-31 14:25 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val request = AssignPlayerQuestUsecase.Request(playerId = playerA.id, questId = notExistQuest)
ditto : request

2023-10-31 14:25 UTC, shmily7829 requested changes
Review done.

2023-10-31 14:25 UTC, shmily7829 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        assertThat(presenter.executedTag).isTrue
1. 移除多餘空行
2. missions.first() 抽成變數較好理解
3. Nit: 測試 Mission Size 應在其他的測試案例測試

2023-10-31 14:25 UTC, shmily7829 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    var executedTag = false
Nit: bool 變數用 is 開頭的變數命名

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/listeners/MemberJoinListener.kt
>              val player = user.toPlayer() ?: return
這個 toPlayer 有副作用，沒有玩家會註冊玩家，可能之後會發一個解決這問題的pr
我會加 TODO

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/listeners/MemberJoinListener.kt
> +            val request = AssignPlayerQuestUsecase.Request(user.id, unlockAcademyQuestId)
這個 usacase 不是只能接 unlockAcademyQuest 而已。

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/listeners/MemberJoinListener.kt
> +            val presenter = AssignPlayerQuestPresenter(user)
以後不會再 listener 拿出 domain 物件了

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/listeners/presenters/AssignPlayerQuestPresenter.kt
> +    override fun presentAssignPlayerMission(mission: Mission) {
以後會有期他的 presenter，你要怎麼不撞名?

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/usecase/AssignPlayerQuestUsecase.kt
> +                .build()
後面的 message 提供詳細的意圖，不然 debug 會不知道找 player 要做甚麼

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    }
我這裡不知道為啥沒有你說的功能

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    }
阿災 我這裡沒有成功清掉

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `success assign a unlock quest to player A`() {
想不到怎麼寫成 given when then

2023-10-31 15:48 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        playerRepository.savePlayer(playerA)
不是每個 test 都會用到 playerA

2023-10-31 15:51 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/domain/exception/AssignedQuestException.kt
> +    RuntimeException("Player already owns this quest. {playerId:${playerId}, questId:$questId}")
down

2023-10-31 15:51 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/achievement/it/AchievementIntegrationTest.kt
> +
down

2023-10-31 15:51 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/usecase/AssignPlayerQuestUsecase.kt
> +    )
down

2023-10-31 15:58 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        val request = AssignPlayerQuestUsecase.Request(playerId = playerA.id, questId = UNLOCK_QUEST_ID)
我認為 request 不應該被共用，不是所有測試都會用到這個 request

2023-10-31 16:00 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +        assertThat(presenter.executedTag).isTrue
down

2023-10-31 16:11 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +            assignPlayerQuestUsecase.execute(request, presenter)
down

2023-11-01 16:46 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/usecase/AssignPlayerQuestUsecase.kt
> +                .build()
resourse no found ... $message 一個句子

2023-11-01 16:46 UTC, wow890209 commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `success assign a unlock quest to player A`() {
given 玩家A 沒有 quest
when 玩家A 接 quest
then 玩家成功接取任務

2023-11-05 06:12 UTC, m1a2st requested changes

2023-11-05 06:12 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `success assign a unlock quest to player A`() {
這裡沒改到

2023-11-05 06:12 UTC, m1a2st commented on utopia-gamification/src/test/kotlin/tw/waterballsa/utopia/utopiagamification/quest/it/AssignPlayerQuestUsecaseTest.kt
> +    fun `fail assign a quest to player A, because quest is not exist`() {
ditto : given when then

2023-11-05 13:00 UTC, m1a2st requested changes
Review done

2023-11-12 06:05 UTC, wow890209 commented on utopia-gamification/src/main/kotlin/tw/waterballsa/utopia/utopiagamification/quest/listeners/SlashCommandListener.kt
> +                presenter.viewModel?.publishToUser(user)
這邊只是把 db 的東西找出來，印出去而已

2023-11-12 08:37 UTC, m1a2st approved these changes
LGTM

2023-11-15 14:44 UTC, shmily7829 approved these changes
LGTM

2023-11-15 14:45 UTC, merged