✨ Manage subscriber role  #205
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #219
Opened 2023-11-05 09:54 UTC by WayneTsou85

## Why need this change? / Root cause: 
- add manage subscriber role feature
## Changes made:
-  resolved #205 
## Test Scope / Change impact:
- manage subscriber role module

2023-11-05 10:48 UTC, wow890209 requested changes
Review down.

2023-11-05 10:48 UTC, wow890209 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +    }
待討論，記得加 todo 和補充

2023-11-05 10:48 UTC, wow890209 commented on main/src/main/resources/wsa.prod.properties
> -wsa-guideline-channel-id=1042774419371720715
沒有最後一行，參見 https://github.com/Waterball-Software-Academy/WSA-Utopia-Discord-Bot/wiki/No.1-%E5%81%9A%E5%A5%BD%E8%A8%AD%E5%AE%9A-IDE-Tool-%E5%8F%8A%E5%BB%BA%E7%AB%8B%E9%96%8B%E7%99%BC%E7%92%B0%E5%A2%83#%E7%AC%AC%E4%BA%8C%E5%8B%95-%E8%A8%AD%E5%AE%9A%E8%87%AA%E5%8B%95%E5%8C%96%E5%AD%98%E6%AA%94

2023-11-05 10:55 UTC, Wally5077 requested changes
**Review done.**

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +    }
```kotlin
    /**
     * "1️⃣"：軟體英文派對訂閱者
     * "2️⃣"：遊戲微服務計畫訂閱者
     * "3️⃣"：純函式咖啡訂閱者
     * "4️⃣"：技術演講吐司會訂閱者
     * "7️⃣"：CS Lab 訂閱者
     */
    private val emojiToSubscriberRoleId = hashMapOf(
            "1️⃣" to wsa.wsaSECSubsriberMemberRoleId,
            "2️⃣" to wsa.wsaGaaSSubscriberRoleId,
            "3️⃣" to wsa.wsaPurefuncSubscriberRoleId,
            "4️⃣" to wsa.wsaTTMSubscriberRoleId,
            "7️⃣" to wsa.wsaCSLabSubscriberRoleId,
    )
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +                val user = UserSnowflake.fromId(userId)
**UserSnowflake** 看起來不像 **User**，如果想要這邊命名是 **User** 的話，或許可以使用下列 Code
```kotlin
val user = User.fromId(userId)
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +                val role = jda.getRoleById(this)?: return
如果這邊需要 `jda.getRoleById(subscriberRoleId)`，也許你可以為 **GenericMessageReactionEvent** 擴充 **Role** 屬性
```kotlin
val role = role ?: return
```

```kotlin
private val GenericMessageReactionEvent.role: Role?
    get() = emojiToSubscriberRoleId[emoji.name]?.let { jda.getRoleById(it) }
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +                handleSubscriberRole(guild, user, role)
也許你可以增加為 **manageSubscriberRole**，增加第二個型態為  **log: (role: Role) -> Unit** 的參數
這樣你就可以如同下方的 Code
```kotlin
        handleSubscriberRole(user, role)
                .queue { log(role) }
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AbstractManageSubscriberRole.kt
> +                                                                        handleSubscriberRole: (guild: Guild, userSnowflake: UserSnowflake, role: Role) -> Unit) {
1. **Guild** -> 已經是個註冊過的 Bean 了，可以由建構子注入
2. 也許你會需要想要這個函數簽章，讓調用方使用方便一些
```kotlin
protected fun GenericMessageReactionEvent.manageSubscriberRole(handleSubscriberRole: (user: UserSnowflake, role: Role) -> RestAction<Void>, log: (role: Role) -> Unit)
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AddSubscriberRoleListener.kt
> +        }
```kotlin
        with(event) {
            manageSubscriberRole(guild::addRoleToMember) {
                logger.info { "[Add Role] {\"userId\":\"${userId}\", \"roleName\":\"${it.name}\" }" }
            }
        }
```

2023-11-05 10:55 UTC, Wally5077 commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/RemoveSubscriberRoleListener.kt
> +        }
```kotlin
        with(event) {
            manageSubscriberRole(guild::removeRoleFromMember) {
                logger.info { "[Remove Role] {\"userId\":\"${userId}\", \"roleName\":\"${it.name}\" }" }
            }

        }
```

2023-11-05 14:19 UTC, WayneTsou85 commented on main/src/main/resources/wsa.prod.properties
> -wsa-guideline-channel-id=1042774419371720715
想了解一下這個需要調整什麼呢？

2023-11-06 15:30 UTC, m1a2st requested changes
review done

2023-11-06 15:30 UTC, m1a2st commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/AddSubscriberRoleListener.kt
> +                        logger.info { "[Add Role] {\"userId\":\"${user.id}\", \"roleName\":\"${role.name}\" }" }
使用 kotlin 的語法 `"""[Add Role]... """` 就不需使用跳脫字元

2023-11-06 15:30 UTC, m1a2st commented on manage-subscriber-role/src/main/kotlin/tw/waterballsa/utopia/managesubscriberole/RemoveSubscriberRoleListener.kt
> +                        logger.info { "[Remove Role] {\"userId\":\"${user.id}\", \"roleName\":\"${role.name}\" }" }
ditto : 不使用跳脫字元

2024-08-17 12:53 UTC, closed without merging