GaaS/recording-participants
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #51
Opened 2023-04-05 15:04 UTC by akechetaki10736

# 因為之前 @Johnny850807 需要緊急 Hotfix 刪掉了之前的 Commit，故重發 PR
## Why need this change? / Root cause: 
- GaaS 需要紀錄讀書會出缺席情況，追蹤成成員活躍度作為剔除與否依據。
- 當 GaaS 讀書會活動開始時，會在活動時間（9 - 10 PM）定期查閱**學院節目區**的出席人員並記錄。
## Changes made:
- Add a new module "gaas".
- Add a new feature "AbsenceReord"
## Test Scope / Change impact:
- gaas

2023-04-06 16:18 UTC, chen-tf commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +}
這邊的三個 event listener 命名風格好像沒有對齊
是否考慮統一使用 `whenXXXXThenYYYY` 或者是 `xxxEvent` 的格式？

2023-04-06 17:16 UTC, Wally5077 requested changes
Review done.

2023-04-06 17:16 UTC, Wally5077 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +    }, getTaipeiTime(start), 3.minutes.inWholeMilliseconds)
詳見底下擴充方法
`start.toDate()`

2023-04-06 17:16 UTC, Wally5077 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +        }, getTaipeiTime(end)
詳見底下擴充方法
```kotlin
end.toDate()
```

2023-04-07 00:06 UTC, hokou approved these changes
Sounds Good To Me.

2023-04-07 04:38 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +fun whenGaaSEventStartsThenRecordTheParticipationStatus() = listener {
done

2023-04-07 04:38 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +                recordEventParticipationStats()
done

2023-04-07 04:38 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +            .takeIf { it.isStudyCircleEvent() && (it.status == ScheduledEvent.Status.CANCELED || it.status == ScheduledEvent.Status.COMPLETED) }
done

2023-04-07 04:39 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +                gaaSEventIds.remove(id)
done

2023-04-07 04:47 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +    val now = getTaipeiCurrentDateTime()
done

2023-04-07 04:47 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +    val end = now.withHour(22).withMinute(0).withSecond(0)
done

2023-04-07 04:47 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +            checkNotNull(channel)
done

2023-04-07 04:47 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +private fun getTaipeiTime(localDateTime: LocalDateTime): Date = Date.from(localDateTime.atZone(ZoneId.systemDefault()).toInstant())
done

2023-04-07 04:47 UTC, akechetaki10736 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/RecordingParticipants.kt
> +private fun getTaipeiCurrentDate(): LocalDate = LocalDate.now()
done

2023-04-07 06:16 UTC, Wally5077 requested changes
Review done.

2023-04-07 09:19 UTC, Wally5077 approved these changes
LGTM

2023-04-07 09:20 UTC, merged