1A2B猜數字遊戲
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #53
Opened 2023-04-06 09:22 UTC by wow890209

## Why need this change? / Root cause: 
-增加1A2B小遊戲
## Changes made:
-完成1A2B遊戲邏輯和流程
-將猜數字頻道ID放到main properties文件
## Test Scope / Change impact:
-測試1A2B的判斷規則

2023-04-06 09:49 UTC, akechetaki10736 requested changes
done.

2023-04-06 09:49 UTC, akechetaki10736 commented on guessNum1A2B/src/main/kotlin/listener.kt
> +        if (channel.id != guessNumberChannelId || message.author.isBot) return@on
Don't omit curly braces.

2023-04-06 09:49 UTC, akechetaki10736 commented on commons/src/main/kotlin/tw/waterballsa/utopia/commons/config/WsaDiscordProperties.kt
> +            wsaGuessNumberChannelId=getProperty("wsa-guess-number-channel-id")
Plz format your code.

2023-04-06 09:49 UTC, akechetaki10736 commented on guessNum1A2B/src/main/kotlin/domain/guessNum1A2B.kt
> +        if (number.length != 4) return "0A0B"
Don't omit curly braces.

2023-04-06 09:49 UTC, akechetaki10736 commented on main/pom.xml
> +            <artifactId>guessNum1A2B</artifactId>
In xml, use dash instead of camel case.

2023-04-06 09:49 UTC, akechetaki10736 commented on pom.xml
> +        <module>guessNum1A2B</module>
ditto

2023-04-06 09:49 UTC, akechetaki10736 commented on pom.xml
> +                <artifactId>guessNum1A2B</artifactId>
ditto

2023-04-06 09:57 UTC, chen-tf requested changes

2023-04-06 09:57 UTC, chen-tf commented on guessNum1A2B/src/test/kotlin/domainTest.kt
> +}
- 分成不同的情境，可以增加測試案例的可讀性，別全部一口氣寫在一個測試案例中
1. 單純Ａ
2. 單純 B
3. 有Ａ有Ｂ
4. 沒有Ａ也沒有Ｂ
5. 猜中數字
- 使用 `assertEquals`

2023-04-06 11:55 UTC, Wally5077 requested changes
Review done.

2023-04-08 10:29 UTC, frankvicky requested changes

2023-04-08 10:29 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/domain/GuessNum1A2B.kt
> +    return (0..9).shuffled().take(4).joinToString("")
`fun generateSecretNumber(): String = (0..9).shuffled().take(4).joinToString("")`

2023-04-08 10:29 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/listener.kt
> +        if (message.contentDisplay.length != 4 || !message.contentDisplay.matches("\\d+(\\.\\d+)?".toRegex())) {
`!message.contentDisplay.matches("\\d+(\\.\\d+)?".toRegex())`
封裝，不然看不懂

2023-04-09 06:16 UTC, Johnny850807 requested changes
Review done

2023-04-09 06:16 UTC, Johnny850807 commented on guess-num-1A2B/src/main/kotlin/listener.kt
> +        if (getEnv("DEPLOYMENT_ENV") != "beta") {
1. 常數化放在 WsaProperties 中

`getEnv(DEPLOYMENT_ENV_KEY) != ENV_BETA`

2.  另外不要在每個 `on {...}` 區塊中去判斷是否位於 beta 環境，直接在函數中的第一行判斷就行了

```kotlin
fun GuessNum1A2BListerner(wsa: WsaDiscordProperties, jda: JDA) = listener {
    if (getEnv(DEPLOYMENT_ENV_KEY) != ENV_BETA) {
        return
    }
    
    on ...
}
```

2023-04-10 15:45 UTC, chen-tf commented
請先處理 
### Conflicting files

- commons/src/main/kotlin/tw/waterballsa/utopia/commons/config/WsaDiscordProperties.kt
- main/src/main/resources/wsa.beta.properties
- pom.xml

2023-04-14 12:57 UTC, closed without merging