:sparkles: 實作提取數 GaaS 數據的 Feature
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #62
Opened 2023-04-15 05:36 UTC by frankvicky

## Why need this change? / Root cause: 
- 方便 GaaS 查閱活動數據
## Changes made:
- gaas
## Test Scope / Change impact:
![image](https://user-images.githubusercontent.com/51072200/232185367-6248fadb-a010-41fb-9ab3-50dfaec152c3.png)

2023-04-15 11:13 UTC, Jacky0428 requested changes
Review done.

2023-04-15 17:13 UTC, Wally5077 requested changes
Review done.

2023-04-15 17:13 UTC, Wally5077 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/QueryEventStats.kt
> +                    .addOption(OptionType.STRING, OPTION_EVENT_DATE, "The event date. Format: yyyy-MM-dd", true)
Option 應該使用數字，讓使用者填寫三個數字，分別為年、月、日

2023-04-15 17:13 UTC, Wally5077 commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/QueryEventStats.kt
> +        }
NIT：看看這樣可不可以
```kotlin
        val avgAndMax = eventStatsFile
                .readLines()
                .filter { line -> line.contains("Avg:") || line.contains("Max:") }
                .joinToString(System.lineSeparator())
        
        replayEphemerally(avgAndMax)
```

2023-04-16 08:21 UTC, Wally5077 approved these changes
LGTM

2023-04-16 08:22 UTC, merged