新增1a2b小遊戲
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #65
Opened 2023-04-16 10:19 UTC by wow890209

## Why need this change? / Root cause: 
-新增1a2b小遊戲
## Changes made:
-
## Test Scope / Change impact:
-

2023-04-16 15:57 UTC, Wally5077 requested changes
Review done.

2023-04-16 15:57 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +    fun unregister(member: Member, channel: ThreadChannel) {
ditto **Discord Model 轉成自己的 Model**

2023-04-16 15:57 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +            "[GameRepository unregister event] " + "{" + "\"feature\" : \"guess-num-1a2b\"," + "\"game room count\" : \"${gameRooms.size}\"," + "}"
```kotlin
"[GameRoom Unregistered]  { \"gameRoomCount\" : \"${gameRooms.size}\"}"
```

2023-04-16 15:57 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +        val deleteRoom = gameRooms.filter { room ->
deleteRoom -> unregisteredGameRoom

2023-04-16 15:57 UTC, Wally5077 commented on guess-num-1A2B/src/test/kotlin/domainTest.kt
> +}
這是 ChatGPT 產的
```kotlin
class GuessNum1A2BTest {
    private val secretNumber = "1234"
    private val game = GuessNum1A2B(secretNumber)

    @Test
    fun `test when guess has only As`() {
        assertGuessResult("1567", "1A0B")
        assertGuessResult("1267", "2A0B")
        assertGuessResult("1236", "3A0B")
        assertGuessResult("1234", "4A0B")
    }

    @Test
    fun `test when guess has only Bs`() {
        assertGuessResult("5671", "0A1B")
        assertGuessResult("5621", "0A2B")
        assertGuessResult("5321", "0A3B")
    }

    @Test
    fun `test when guess has both As and Bs`() {
        assertGuessResult("1423", "1A3B")
        assertGuessResult("1243", "2A2B")
    }

    @Test
    fun `test when guess has neither As nor Bs`() {
        assertGuessResult("7890", "0A0B")
        assertGuessResult("123", "0A0B")
        assertGuessResult("12345", "0A0B")
    }

    @Test
    fun `test when guess is the same as the secret number`() {
        assertGuessResult(secretNumber, "4A0B")
    }

    @Test
    fun `test with invalid guess input`() {
        assertThrows<IllegalArgumentException> { game.guess("12a4") }
        assertThrows<IllegalArgumentException> { game.guess("12345") }
        assertThrows<IllegalArgumentException> { game.guess("12") }
        assertThrows<IllegalArgumentException> { game.guess("") }
    }

    private fun assertGuessResult(guess: String, expected: String) {
        val result = try {
            game.guess(guess)
        } catch (ex: IllegalArgumentException) {
            throw AssertionError("Input validation failed for guess $guess", ex)
        }
        assertEquals(expected, result)
    }
}
```

2023-04-17 04:28 UTC, frankvicky requested changes

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +val repository = GameRepository()
private

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +class GameRoom(val member: Member, val threadChannel: ThreadChannel) {
`(private  val member: Member, private val threadChannel: ThreadChannel)`

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +        }
when

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +            result += "恭喜猜對!"
String interpolate

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +    }
```kotlin
threadChannel.run {
    // action
}
```

2023-04-17 04:28 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/listener.kt
> +            }
```kotlin
repository.find(member!!)?.let { 
    //action 
}
```

2023-04-23 12:53 UTC, closed without merging