Feat/random lottery
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #67
Opened 2023-04-16 20:31 UTC by w305jack

## Why need this change? / Root cause: 
- Lottery，可以在當下頻道，隨機挑選指定人數
## Changes made:
-
## Test Scope / Change impact:
-

2023-04-17 10:24 UTC, frankvicky requested changes

2023-04-17 10:24 UTC, frankvicky commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +        val members = mainChannel.members.filter { (role == null || it.roles.contains(role)) && !it.user.isBot }
Boolean 表達式可以封裝起來，比較好讀

2023-04-17 10:24 UTC, frankvicky commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +fun <MemberImpl> getRandomMember(list: Collection<MemberImpl>, x: Int): List<MemberImpl> = list.shuffled().take(x)
為什麼泛型要指定 MemberImpl ？

2023-04-17 12:03 UTC, Johnny850807 requested changes
Review done

2023-04-17 12:12 UTC, Wally5077 approved these changes
LGTM

2023-04-17 20:03 UTC, w305jack commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +        val members = mainChannel.members.filter { (role == null || it.roles.contains(role)) && !it.user.isBot }
已封裝成 isQualifiedMember 方法，來判斷合格的 member

2023-04-17 20:03 UTC, w305jack commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +fun <MemberImpl> getRandomMember(list: Collection<MemberImpl>, x: Int): List<MemberImpl> = list.shuffled().take(x)
已修正為 T

2023-04-17 20:03 UTC, w305jack commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +    on<SlashCommandInteractionEvent> {
Done

2023-04-18 00:38 UTC, hokou approved these changes
LGTM

2023-04-18 01:35 UTC, Wally5077 commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +fun <MemberImpl> getRandomMember(list: Collection<MemberImpl>, x: Int): List<MemberImpl> = list.shuffled().take(x)
這邊是指使用抽象的 interface `Member`

2023-04-18 02:03 UTC, frankvicky requested changes

2023-04-18 02:03 UTC, frankvicky commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +private fun <T> getRandomMember(list: Collection<T>, x: Int): List<T> = list.shuffled().take(x)
這邊有幾個建議

`private fun <T> getRandomMember(list: Collection<T>, x: Int): List<T> = list.shuffled().take(x)`

可以使用 Kotlin Ext 改寫會更好，有兩種調整方式，一種是你這個方法只給 Member 用：
`private fun Collection<Member>.getRandomMember(x: Int): Collection<Member> = shuffled().take(x)`

另一種是你把這個方法開放給大家用：
`fun Collection<T>.getRandomElement(x: Int): Collection<T> = shuffled().take(x)`

要注意的是你如果採用第二種作法，你需要把這個方法移動到 common 模組。

2023-04-18 02:03 UTC, frankvicky commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +    (role == null || member.roles.contains(role)) && !member.user.isBot
這邊也可以用 Kotlin Ext 改寫，改完之後你使用會是下面這樣：
`member.isQualifiedMember(role)`

至於怎麼改可以參考上面或上網看一下😉

2023-04-18 02:41 UTC, Wally5077 commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +private fun <T> getRandomMember(list: Collection<T>, x: Int): List<T> = list.shuffled().take(x)
我的想法是偏向採取最後一種泛型的作法會好一點
這樣 @wow890209、@hokou 以及未來一些 Random 方面的操作，或許能用得上

2023-04-18 13:13 UTC, w305jack commented on random/src/main/kotlin/tw/waterballsa/utopia/random/Lottery.kt
> +    (role == null || member.roles.contains(role)) && !member.user.isBot
了解，看 comment，長知識
我會再調整 👌

2023-04-19 01:47 UTC, frankvicky approved these changes
LGTM

2023-04-26 14:41 UTC, Johnny850807 approved these changes
LGTM

2023-04-26 14:43 UTC, merged