Knowledge king kickoff (#7)
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #69
Opened 2023-04-23 11:24 UTC by wow890209

* kickoff 5 acts

* :construction: complete the first workable version

---------

## Why need this change? / Root cause: 
-
## Changes made:
-
## Test Scope / Change impact:
-

2023-04-23 13:23 UTC, frankvicky requested changes
Review Done.

2023-04-23 13:23 UTC, frankvicky commented on commons/src/main/kotlin/tw/waterballsa/utopia/commons/extensions/TimerExtension.kt
> +    }, time, 24.hours.inWholeMilliseconds) // 24 hours in milliseconds
請參考 kotlin.concurrent.timerTask

2023-04-23 13:23 UTC, frankvicky commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt
> +                    }
為什麼多縮一排？

2023-04-23 13:23 UTC, frankvicky commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt
> +                }
ditto

2023-04-23 13:23 UTC, frankvicky commented on gaas/src/main/kotlin/tw/waterballsa/utopia/gaas/PersonalLeave.kt
ditto

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/ChatGptQuestionParser.kt
> +                println(err)
改用 log

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/ChatGptQuestionParser.kt
> +            var optionRawString: String = ""
讓 Kotlin 自己幫你判斷型別

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/ChatGptQuestionParser.kt
> +                        optionRawString.lines().subList(0, 4).map {
subList 改成 take

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/ChatGptQuestionParser.kt
> +                            option
inline

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +    val id: String = UUID.randomUUID().toString()
ditto

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +    private var currentQuestionStartTimeInMillis: Long = 0
ditto

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +            val secondsElapsed = (currentTimeMillis() - currentQuestionStartTimeInMillis).milliseconds.inWholeSeconds
`(currentTimeMillis() - currentQuestionStartTimeInMillis).milliseconds.inWholeSeconds`
請封裝，有點難讀

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +    }
`fun isGameOver(): Boolean = gameOver`

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +}
一個類別一個檔案

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +abstract class Answer(open val timestamp: Date) {
這邊  `open val timestamp: Date` 是想讓別人繼承？
是的話用 abstract 修飾

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKing.kt
> +}
Data Class 盡量不要使用繼承。

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/domain/events.kt
> +}
ditto

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/listeners.kt
> +
這邊可以只用 joinToString 就達到一樣的效果

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/listeners.kt
> +}
`private fun generateTopic(): String = "Computer Science"`

2023-04-23 13:23 UTC, frankvicky commented on knowledge-king/src/main/kotlin/tw/waterballsa/utopia/knowledgeking/listeners.kt
> +        }
只有一個條件用 If 就好

2023-04-23 16:05 UTC, frankvicky requested changes

2023-04-23 16:05 UTC, frankvicky commented on knowledge-king/src/test/kotlin/tw/waterballsa/utopia/knowledgeking/domain/KnowledgeKingTest.kt
> +            }
這啥？

2023-04-23 16:11 UTC, Wally5077 approved these changes
LGTM

2023-05-06 07:00 UTC, Johnny850807 commented
Jack takes this

2023-05-06 07:00 UTC, closed without merging