新增1a2b小遊戲
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #81
Opened 2023-05-10 14:57 UTC by wow890209

## Why need this change? / Root cause: 
- 修改程式碼
    - 原本functional的寫法改用class的寫法
    - 改用event bus的寫法
## Changes made:
-
## Test Scope / Change impact:
-

2023-05-11 02:40 UTC, frankvicky commented
CI 沒過

2023-05-11 03:44 UTC, wow890209 commented
修好了

2023-05-11 06:03 UTC, Wally5077 requested changes
Review done.

2023-05-11 11:37 UTC, Johnny850807 requested changes
Good job! Review done

2023-05-11 11:37 UTC, Johnny850807 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameRepository.kt
> +        }
1. 不用每一件事都用「事件」來稱呼他喔，因為他們只是「步驟」不是事件～！
2. 另外，logger 會幫忙顯示 file, class name，你不用重複打在 log 中。

so please rewrite to `"[register] {  \"hostId\" : \"${memberId}\" }"`

2023-05-11 11:37 UTC, Johnny850807 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameRepository.kt
> +class GameRepository {
`GameManager`  is better

因為 Repository 這個字通常象徵著：
1. data layer 的抽象
2. 聚合根的持久化

而你的程式碼中，兩者應該都不是

2023-05-11 11:40 UTC, Wally5077 requested changes
Review done.

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/domain/GuessNum1A2B.kt
> +        val result = listOf(AnsweredEvent("${a}A${b}B"))
`result` -> `events`

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/domain/GuessNum1A2B.kt
> +    private val memberId: String,
playerId

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameRepository.kt
> +    fun register(memberId: String): List<Event> {
playerId

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameRepository.kt
> +    fun unregister(memberId: String) {
ditto playerId

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameRepository.kt
> +    fun find(memberId: String): GuessNum1A2B? {
ditto playerId

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/guessNum1A2BListener.kt
> +            val game = repository.find(member?.id!!)!!
你怎能保證接到的訊息，一定是從「房主」發出來的？

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/guessNum1A2BListener.kt
> +                val channel = createRoom()
`channel` -> `room`

2023-05-11 11:40 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/guessNum1A2BListener.kt
> +    }
應該放在其他調用 `closeRoom` 的方法下

2023-05-11 12:34 UTC, Johnny850807 approved these changes
最後一個 comment，改完不用和我說，LGTM

2023-05-11 12:34 UTC, Johnny850807 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/guessNum1A2BListener.kt
> +class GuessNum1A2BListener : UtopiaListener() {
檔案名字改成 `GuessNum1A2BListener`
開頭要大寫

2023-05-11 12:50 UTC, Wally5077 requested changes
Review done.

2023-05-11 12:50 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GameManager.kt
> +        return gameRooms[playerId]!!
這不用重新取，只許要將第 10 行的 GuessNum1A2B 宣告變數承接，並且將其回傳就好

2023-05-11 12:50 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/domain/GuessNum1A2B.kt
> +    private val secretNumber: String = generateAnswer()
`answer`

2023-05-11 14:26 UTC, frankvicky approved these changes
LGTM

2023-05-13 14:25 UTC, Wally5077 requested changes
Review done.

2023-05-13 14:25 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GuessNum1A2BListener.kt
> +            if (game.isValidRoomId(room.id)) {
`isValidRoomId` 是多餘的封裝

2023-05-13 14:31 UTC, frankvicky requested changes

2023-05-13 14:31 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GuessNum1A2BListener.kt
> +            }
`game?.let { ... } ?: run { ... }`

2023-05-13 14:31 UTC, frankvicky commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GuessNum1A2BListener.kt
> +            }
ditto

2023-05-14 10:07 UTC, frankvicky approved these changes

2023-05-14 14:31 UTC, Wally5077 approved these changes
LGTM

2023-05-14 14:34 UTC, merged