bugfix 1a2b game
Waterball-Software-Academy/WSA-Utopia-Discord-Bot pull request #91
Opened 2023-05-16 11:20 UTC by wow890209

## Why need this change? / Root cause: 
-新增不是文字頻道的檢查，防止在語音頻道、討論串建立遊戲
## Changes made:
-
## Test Scope / Change impact:
-

2023-05-16 13:18 UTC, Wally5077 requested changes
Review done.

2023-05-16 13:18 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GuessNum1A2BListener.kt
> +        if (isVaild && channel is TextChannel) {
`channel is TextChannel` 並不屬於 isValidCommandName 的邏輯，你應該放在方法外面

2023-05-16 15:10 UTC, Wally5077 requested changes
Review done.

2023-05-16 15:10 UTC, Wally5077 commented on guess-num-1A2B/src/main/kotlin/tw/waterballsa/utopia/guessnum1a2b/GuessNum1A2BListener.kt
> +        return null
`if channel is ThreadChannel channel.asThreadChannel() else null`

2023-05-17 05:58 UTC, Wally5077 approved these changes
LGTM

2023-05-17 06:17 UTC, frankvicky approved these changes

2023-05-17 10:54 UTC, merged